{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-coordinates
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - biom-format
    - pandas
    - matplotlib
    - scipy
    - cartopy==0.19
    - numpy
    - geopy
    - dill
    - pysal==2.1.0
    - scikit-bio
    - pandana 
    - urbanaccess
    - q2templates {{ version }}.*
    - q2-types {{ version }}.*
    - qiime2 {{ version }}.*

test:
  imports:
    - q2_coordinates
    - qiime2.plugins.coordinates

about:
  home: https://github.com/bokulich-lab/q2-coordinates
  license: BSD-3-Clause
  license_family: BSD
